# Dependencies
markdown:         redcarpet

# Match github
safe:             true
lsi:              false
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            CoaDH
tagline:          'Confessions of a Disorderly House'
description:      'C++ and other geekery'
url:              http://alamaison/alamaison.github.io
author:
  name:           'Alexander Lamaison'
  url:            https://twitter.com/DisorderlyHouse

paginate:         1

# Custom vars
github:
  repo:           https://github.com/alamaison
