# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Confessions of a Disorderly House
tagline:          'C++ and other geekery'
#description:      'Base theme for Jekyll themes by @mdo.'
url:              http://alamaison/alamaison.github.io

author:
  name:           'Alexander Lamaison'
  url:            https://twitter.com/DisorderlyHouse

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/alamaison
